### ISSUE TITLE
how can i use "import time" in ytt  engine?

### ISSUE THREAD

**Issue by tywldx** [k14s/ytt#100]
Hi:
  I want to get the timestamp in my function
this`s my code:
file name: *.star
```python
import time
def testfunc():
  return int(time.time())
end
```
 but i got an error like this:
```
 - (p) Lines are 1 based
```
i need some help!

**Comment by ewrenn8** [comment]
There are a few issue going on here:

 The panic you are seeing is being cause by a bug. I opened an issue (#101) to fix this.

The cause of the syntax error here is that `ytt` does not support `import`. You need to use the [`load`](https://github.com/k14s/ytt/blob/master/docs/lang-ref-load.md) function to load other modules. 

Finally, `ytt` doesnt provide the ability to work with time (nor networking, disk, etc) in order to produce more deterministic outcomes and improve security. In order to get the time, it would need to be passed in as a data value like other inputs.

**Comment by tywldx** [comment]
> There are a few issue going on here:
> 
> The panic you are seeing is being cause by a bug. I opened an issue (#101) to fix this.
> 
> The cause of the syntax error here is that `ytt` does not support `import`. You need to use the [`load`](https://github.com/k14s/ytt/blob/master/docs/lang-ref-load.md) function to load other modules.
> 
> Finally, `ytt` doesnt provide the ability to work with time (nor networking, disk, etc) in order to produce more deterministic outcomes and improve security. In order to get the time, it would need to be passed in as a data value like other inputs.

Thank you for your answer.

I decided  my system create ```data.values.timestamp``` by self and insert it into the yaml file before calling ```ytt```  to solve this problem
