### ISSUE TITLE
question: load plain yaml (without enclosing function)

### ISSUE THREAD

**Issue by fabriziopandini** [k14s/ytt#102]
The playground example https://get-ytt.io/#example:example-load  shows how it is possible to load functions that return YAML fragments.

Question: Is it possible to load yaml from external files, without wrapping yaml in functions? How?

**Comment by cppforlife** [comment]
@fabriziopandini you could do something like this:

config.yml
```yaml
#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

some_yaml: #@ yaml.decode(data.read("other.yml.file"))
```

and executing `ytt -f config.yml -f other.yml.file` (note that i changed ext on other.yml.file, so that ytt doesnt include it in the output by itself; you could also use file marks to mark it off as not for output).

also above method wouldnt really work for yaml files that include multiple documents (since yaml.decode errors when encountering more than one doc)

another option is to do something like https://get-ytt.io/#example:example-ytt-library-module. where separate yaml is treated as a library.

if you dont mind, please elaborate on what you are trying to do (for possible improvements to ytt or alt ways)

**Comment by fabriziopandini** [comment]
@cppforlife thanks for the quick answer!
I'm a newbie of ytt which is playing with the tool trying to collect some insight for answering to https://github.com/kubernetes-sigs/cluster-api/issues/2339. 

What I'm trying to do is to understand what is the best way to break down a big YAML template, into several, smaller templates that should be included in the first. e.g.

A cluster API - cluster template is composed by 3 group of kubernetes objects (cluster resources, control-plane nodes resources, worker nodes resources), and I would like to define each group is in a separate sub-template (see the resulting output https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/releases/download/v0.6.0-rc.1/cluster-template.yaml) 

I filed the question because:
- I find it counter-intuitive to be forced to wrap the YAML that defines sub-template into a function, especially considering that ytt nicely understand the structure of the top-level YAML
- I have potential use cases where the secondary YAML are generated by other tools, so it is not possible/easy to add ytt specific syntax

It would be great to have something like

```
#@ include("secondary.yaml", var)
```

With var being a simple var or a list so we can manage also the case when "secondary.yaml" has multiple documents

**Comment by cppforlife** [comment]
@fabriziopandini back from the weekend... ive checked out cluster-template.yaml and im trying to understand for which cases you would need something like `include(...)`. it seems that what you describe in your comment could be just achieved by `ytt -f file1.yml -f file2.yml ...`.

**Comment by timothysc** [comment]
@fabriziopandini - I think the library module example should suffice for CAPI, and would make it easier for downstream providers to easily import.
