### ISSUE TITLE
add --output-files flag to add output files into existing directory

### ISSUE THREAD

**Issue by Naatan** [k14s/ytt#145]
No warning, no prompt, no nothing. I don't see why it needs to delete anything other than file conflicts, but it should at the very least give a warning.

My use-case is I want a README.md in the target directory, which now gets deleted any time I generate yamls.

**Comment by cppforlife** [comment]
> I don't see why it needs to delete anything other than file conflicts

one of the reasons it was changed to the way it behaves today is because there is no easy way to clear out previous results that were placed there by ytt before. (e.g. ytt -f ... --output-directory /tmp/foo, make changes to templates, ytt -f ... --output-directory /tmp/foo again). if it's not cleared out, tools downstream will potentially pick up files that arent meant to be picked up.

> but it should at the very least give a warning.

what kind of warning are you thinking about? like a confirmation prompt?

**Comment by Naatan** [comment]
You already aren't allowing the src and target directory to be the same, so isn't the issue you described above already moot? And if not, at the very least you could exclusively target .yml files.

> what kind of warning are you thinking about? like a confirmation prompt?

If you absolutely have to delete files that you cannot establish "ownership" of then yes, some type of confirmation so the end-user has a chance to recover. This could easily lead to significant data loss, luckily all I lost was a readme, the rest was caught by git staging.

**Comment by cppforlife** [comment]
> And if not, at the very least you could exclusively target .yml files.

it really depends on given templates, so it's not just yml files which makes the problem tougher (for example it's common to template some text files in addition to yaml).

> some type of confirmation so the end-user has a chance to recover

my thinking was that --output-directory naming was enough to raise eyebrows about what would happen to the destination directory. possibly, thats not as obvious as i hoped.

> This could easily lead to significant data loss, luckily all I lost was a readme, the rest was caught by git staging.

fair enough. will try to add a confirmation check for this (though it wont be conditional based on directory contents to make things simpler).

**Comment by Naatan** [comment]
Couldn't you just remove the conflicting target files right before you write them ? Yes you would not be able to tell whether those files were in fact written by ytt in the first place, but at least you're only removing files that actually conflict.

And if there's some sort of recursive dependency issue that seems like it should come up as you try to compile the yaml anyway, not something you ought to work around by deleting everything imo.

**Comment by aisbaa** [comment]
This is crazy! This is the first templating engine in my life that deletes all content of output directory.

- Luckily I did not point to file system root.
- Luckily all changes were push to git remote otherwise I would have lost those.
- Luckily I can clone repo again.

Here's how it went:

```
➜ 11:55 ~/Work/monorepo git:(T5975643) ✗ ytt --strict -f kubernetes/manifest/resources/milind.yaml -o yaml --output-directory ./
ytt: Error: unlinkat ./.: invalid argument
➜ 11:55 ~/Work/monorepo ls -la
total 0
drwxr-xr-x   2 aistis  staff    64 May 20 11:55 .
drwxr-xr-x  49 aistis  staff  1568 May 18 12:56 ..
```

There is not warning for this either, not even in **help message**.

```
> ytt --help | grep output-directory
      --output-directory string                    Output destination directory
```

--- 

Sorry for bashing you, I'm pretty sure this is a great tool and thank you for putting effort in development and making it open source. All of this is great. It's just a bit shocking to get repository deleted by templating engine on a first run. I'll avoid ytt for at least a while.

```
➜ 12:10 ~/Work ytt --version
ytt version 0.27.2
```

**Comment by cppforlife** [comment]
oof. tough but i see your point. 

> This is the first templating engine in my life that deletes all content of output directory.

i didnt expect this to be very controversial, but seems i was wrong. may be im too paranoid myself with my day to day usage of various utilities -- my personal default is to assume that whatever resource is given to a utility, it's theirs to recreate/delete/modify in whatever way. that, plus assumption that tools behave deterministically results in the reasoning behind current behaviour.

> Luckily I did not point to file system root.

it already does not allow several common misconfigurations like `/`, `.`, etc.

> There is not warning for this either, not even in help message.

here is the change to rename --output-directory to --dangerous-emptied-output-directory (https://github.com/k14s/ytt/commit/ba71672c8b86903d913e5bdf94914621f78433bb). --dangerous prefix is consistent with some of the other flags in k14s tools. im hoping "emptied" is clear enough that directory will be emptied. couldnt add interactive confirmation since stdin might already be occupied.

**Comment by Naatan** [comment]
Sorry to push back, but that seems like a somewhat lazy solution to the problem, and makes the user experience even more awkward. If I may offer some alternate solutions, with the understanding that stdin cannot be used (though that seems like a technical limitation that should be eliminated);

 - If the target directory is not empty simply error out, then the act of deleting the target directory files is on the end-user 
 - Or better yet; just delete the target file right before writing. There's no sensible reason I can think of why ytt should delete all files in the target directory. Again if src and output files conflict that should become apparent earlier on in the process anyway.

As a general rule I would say you should always avoid recursively deleting directories that you do not have explicit "ownership" of. In this case you don't know what someone might be feeding in as the output directory. And given the use-case of ytt it's not at all unlikely that the target directory will be containing vital project files.

**Comment by cppforlife** [comment]
> with the understanding that stdin cannot be used (though that seems like a technical limitation that should be eliminated)

not sure what you mean by that. stdin stream is singular, so im not sure how one can reuse it for passing data and interactive input without inventing a framing protocol.

> If the target directory is not empty simply error out, then the act of deleting the target directory files is on the end-user

sure, but that would lead to most common use case to be have to written this way:

rm -rf output/
mkdir output/
ytt -f ... --output-directory output/
... do something with output/ ...

that seems to be quite less productive and more error-prone than having a flag that is responsible for resetting destination. technically above example does not even deal with skipping removal of directory if templates fail to render, so it's even more complex.

> Or better yet; just delete the target file right before writing. There's no sensible reason I can think of why ytt should delete all files in the target directory.

you may have to share your use case for this flag. it may not be quite the same as the most common use case that --output-directory targets:

1. ... work with templates ...
2. ytt -f templates --output-directory output/
3. ... remove, add or modify some templates ...
4. ytt -f templates --output-directory output/

if output/ is not reset every time you will have a mix of old and new template results, as nothing would clean up old files from output/ that ytt generated in previous invocations (step 2). that is quite problematic and may even lead to downstream configuration vulnerabilties since configuration result in output/ would not be deterministic (step 4 state is really a result of step2 and step 4, instead of always just being result of step 4).

> avoid recursively deleting directories that you do not have explicit "ownership" of

but that's exactly why we ask the user for output directory, that is for the user to give us ownership of that directory -- not ownership of individual files.

may be its worth adding `--output-files` flag that would be closer to what you are describing -- would create/override individual files disregarding "overall final state" (though i would still be interested in hearing more about use cases when that's useful). even with --output-files one can still lose important data if not being careful which directory is targeted.

**Comment by Naatan** [comment]
> sure, but that would lead to most common use case to be have to written this way:

> rm -rf output/
> mkdir output/
> ytt -f ... --output-directory output/
> ... do something with output/ ...

You don't need to mkdir, ytt can still do that. The only new line would be the rm, and it ensures that the user if fully aware of what's happening. You should not be running `rm -rf` implicitly.

> you may have to share your use case for this flag. 

I shared my use-case here: 

https://github.com/k14s/ytt/issues/145#issuecomment-631071853

> as nothing would clean up old files from output/ that ytt generated in previous invocations 

Cleaning up files should not be the job of ytt though. I'm asking it to generate files, not clean up files. 

> but that's exactly why we ask the user for output directory, that is for the user to give us ownership of that directory -- not ownership of individual files.

In my humble opinion that ownership is neither conveyed properly, desirable nor intuitive.  From my perspective, when I give ytt an output directory I'm telling it "this is where you can write my files". I'm not telling it "this is your directory, go wild!".

I think you're being too presumptuous by putting ytt in charge of cleaning up "my" files, I'm perfectly capable of doing that myself. And by being presumptuous you eliminate any possibility for the user to dictate their own workflow. In my case my output directory cannot have a readme, but I could also see this being problematic if you wanted to run multiple ytt commands that output to a dir, or if you're only using ytt to generate -some- yaml files but not all. 

I would expect a program like this to be unixy; do one thing and do it well. From my perspective that one thing is generate yaml files. Cleaning up build/output directories is not something I would expect from it.

Of course this is all just my opinion, I'm merely trying to share some perspective.

**Comment by cppforlife** [comment]
id like to mention that your input is much appreciated.

i think i have a better understanding how you view this functionality.

one thing i noticed is that i think we have a different way of how we view the "output". when i think of --output-directory flag i think of it as an option to produce single artifact, an entire directory (in other words a single artifact). i dont see it as a flag that produces a set of files (ie multiple artifacts) to be added into a directory. i think of it as a "sibling" to an imaginary flag "--output-stdout" (which also produces single artifact, one stdout stream), or another imaginary flag "--output-ytt-bundle" (which also produces single artifact). this is why i mentioned above may be its worth having --output-files flag (or similar name) to produce multiple separate artifacts (ie files) that go into various places.

> I think you're being too presumptuous by putting ytt in charge of cleaning up "my" files, I'm perfectly capable of doing that myself. And by being presumptuous you eliminate any possibility for the user to dictate their own workflow. ... I would expect a program like this to be unixy; do one thing and do it well. From my perspective that one thing is generate yaml files. Cleaning up build/output directories is not something I would expect from it.

yeah, makes sense. i hope to end up somewhere in the middle of very flexible and very convenient (for common workflows). i could see use case you describe becoming more common as ytt gets used in more widely.

what do you think of having --output-files and --dangerous-emptied-output-directory as flags to cater to these two use cases?

**Comment by Naatan** [comment]
How would `--output-files` work when you feed it multiple input files like so:

```
ytt -f directory-with-multiple-yamls/ 
```

Assume this directory has 2 yaml files in it, which both need to get compiled to their own output file.

Note it sounds like my suggestion of deleting files right before writing to them should address your use-case of `--output-directory` only being used for a single artifact. I'm still not clear on why you want to avoid that as it seems such a logical solution to this problem.

**Comment by cppforlife** [comment]
> How would --output-files work when you feed it multiple input files like so:

it would work exactly how you describe

`ytt -f config/ --output-files /tmp` would produce

```
/tmp/foo.yml
/tmp/blah/blah.yml
```

assuming that there is `config/foo.yml` and `config/blah/blah.yml`. it would not touch anything else in `/tmp`.

> Note it sounds like my suggestion of deleting files right before writing to them should address your use-case of --output-directory only being used for a single artifact

im saying entire directory _in its entirety_ is the artifact (it may contain multiple files). in my use of ytt (and from those ive observed in my neck of the woods), we rarely care about individual files or merging with existing set of files. hence to conveniently support that use case (described here: https://github.com/k14s/ytt/issues/145#issuecomment-631789311), its good to have a flag that "owns" entire directory.

**Comment by Naatan** [comment]
Oh I see, I thought you meant `--output-files` would take arguments for the individual filenames or something. I think that makes sense. I still don't quite understand why you need the two behaviours, but `--output-files` would cover mine and using "dangerous" would give some form of heads up so I think that addresses my concerns.

**Comment by cppforlife** [comment]
added https://github.com/k14s/ytt/commit/e560fd63c3318dc35dd89fd0580bc6446cc83a44

**Comment by cppforlife** [comment]
released in https://github.com/k14s/ytt/releases/tag/v0.28.0. thank you for sharing your insights.
