### ISSUE TITLE
"Load data values" from multiple files but no overlay

### ISSUE THREAD

**Issue by damzog** [k14s/ytt#163]
Hi,

trying to solve the following problem: I want to create a vars.yml file (in order to deploy something with bosh with a templated manifest) and the variables in vars.yml come from different sources, e.g. environment specific settings like proxy, dns and output from terraform.

So I would like to use the "Load data values" feature but with multiple input files. Currently if i do so it triggers the overlay mechanism which complains if the input from different files have different keys. Is there a way to circumvent this?
```

ytt: Error: Overlaying data values (in following order: proxy.yml, dns.yml):
  Document on line dns.yml:2:
    Map item (key 'de') on line dns.yml:3:
      Expected number of matched nodes to be 1, but was 0
```

**Comment by cari-lynn** [comment]
Hi, @damzog,

Because ytt needs to be able to support more complex merging behavior, it currently works by treating the first data values file as a base values file and then applying additional data values as overlays. Data values inputs follow the same ordering as overlays referenced [here](https://github.com/k14s/ytt/blob/develop/docs/lang-ref-ytt-overlay.md#overlay-order). This means you're not able to circumvent this behavior, but it allows you to use annotations to specify the merge behavior. In order to accomplish what you're trying you can use the `#@overlay/match missing_ok=True` annotation in your additional data values files. [Here's](https://get-ytt.io/#gist:https://gist.github.com/pivotal-dean/003700be26a51a28e18a516119703dcc) an example of what that would look like.

Feel free to reach out if this doesn't solve your use case.

**Comment by cppforlife** [comment]
as a shortcut there is also a way to specify missing_ok=True fro the entire document:

```yaml
#@data/values
#@overlay/match-child-defaults missing_ok=True
---
some_new_key: true
```

additionally we are planning to add first-class data values schemas (https://github.com/k14s/ytt/tree/develop/proposals/001-schemas) which in this case would allow multiple schemas to be be merged (assuming there is no conflicting instructions). then you wouldnt have add annotations to let ytt know that this is a new _wanted_ key (a side effect of data values being used to specify and define data values).

finally, we recommend ytt templates to specify _all_ data values used within templates in the base data values (even if there is no clear default). this acts as a way to "define" data values expected. example: https://github.com/cloudfoundry/cf-for-k8s/blob/master/config/values.yml. in most cases when this is done, you no longer have to worry about adding annotations to add new keys down the road.

**Comment by cppforlife** [comment]
closing, feel free to reopen or ping us on slack.
