### ISSUE TITLE
YAML merge keys are not supported, get stripped

### ISSUE THREAD

**Issue by benmoss** [k14s/ytt#238]
YAML merge keys are a [working draft](https://yaml.org/type/merge.html) feature of the YAML spec, but are implemented by a lot of YAML parsing libraries and used somewhat widely in the wild.

ytt doesn't support these, but even more problematically strips them from emitted YAML. If they were retained other downstream tools processing this YAML after ytt could still use/make sense of them.

```
$ cat /tmp/foo.yaml
foo: &foo
  cool: beans

bar:
 <<: *foo
 wow: dude

$ ytt -f /tmp/foo.yaml
foo:
  cool: beans
bar:
  wow: dude

$ yq r -X /tmp/foo.yaml
foo:
  cool: beans
bar:
  wow: dude
  cool: beans
```

**Comment by gcheadle-vmware** [comment]
Hi @benmoss,

Thanks for reaching out and bringing this to our attention. Using the YAML merge key is currently unsupported in ytt, however we want to be able to support this workflow so that you have still use the output as expected. Someone reported this problem in #186, and we are currently waiting on a PR in the go-yaml library which will fix this issue.

**Comment by benmoss** [comment]
Ah cool, I'll close this then! Thanks 😄

**Comment by benmoss** [comment]
This was actually fixed by https://github.com/vmware-tanzu/carvel-ytt/commit/237b7e2
