### ISSUE TITLE
GitOps friendly command for ytt

### ISSUE THREAD

**Issue by braunsonm** [k14s/ytt#260]
**Describe the problem/challenge you have**
Kapp provides a way to deploy all apps in a repo with a simple command. I would like to manage those apps config with ytt, however I would still need to call ytt on each subdirectory. This makes the one liner of kapp not as beneficial when each app uses ytt (or another tool like helm).

https://github.com/vmware-tanzu/carvel-kapp/blob/develop/docs/gitops.md

**Describe the solution you'd like**
Imagine you have a directory structure like so:
```
.
├── app1
│   ├── config
│   │   └── app1-config.yml
│   └── values
│       └── app1-values.yml
├── app2
│   ├── config
│   │   └── app2-config.yml
│   └── values
│       └── app2-values.yml
├── app3
│   ├── config
│   │   └── app3-config.yml
│   └── values
│       └── app3-values.yml
└── values
    └── global-values.yml
```

I would like to be able to have some command like `ytt app-group -f . -f values/` similar to the `kapp app-group` command. This would in turn run the command:
`ytt -f app1/config -f app1/values -f values > app1/app1-rendered.yml`

For each application. The directory structure would finally look like:
```
.
├── app1
│   ├── app1-rendered.yml
│   ├── config
│   │   └── app1-config.yml
│   └── values
│       └── app1-values.yml
├── app2
│   ├── app2-rendered.yml
│   ├── config
│   │   └── app2-config.yml
│   └── values
│       └── app2-values.yml
├── app3
│   ├── app3-rendered.yml
│   ├── config
│   │   └── app3-config.yml
│   └── values
│       └── app3-values.yml
└── values
    └── global-values.yml
```

Then (as long as kapp doesn't explore subdirectories), `kapp app-group deploy -g my-env --directory my-repo` would just work with ytt.

If a directory does not have a `config/` and `values/` folder I would expect the command to ignore that directory.

Obviously this introduces a bit of an opinionated approach for how to structure ytt projects (`config/` and `values/`) however from the projects I have seen, this is generally the structure that is recommended.

**Comment by cppforlife** [comment]
@braunsonm i would recommend making your own script/tiny-tool (e.g. ytt-apps) that delegates to ytt/kapp in appropriate places. ytt-apps would execute ytt for each subdir, but output its results into a separate folder hierarchy. kapp app-group could be used with that rendered folder hierarchy to do the deploy.

alternative approach our team has been investigating is to codify each "app" into App CR  as defined by carvel's kapp-controller (https://github.com/vmware-tanzu/carvel-kapp-controller).

**Comment by braunsonm** [comment]
That's an interesting suggestion @cppforlife I'm curious why you think this doesn't fit in ytt when kapp does the exact same thing that could have been made from a simple script?

**Comment by braunsonm** [comment]
Also apologies but I never really understood where kapp controller fits in.. It doesn't save time on the CI because you still need to setup a CI to push an image from your repository to run the app, it makes configuring the secrets more difficult because another pipeline needs to put those onto the repository (vs a pipeline just looking them up from Vault), and you still need to trigger the controller to redeploy your app when an update occurs if I understand correctly.

That's why we haven't thought about adopting it.

**Comment by cppforlife** [comment]
> I'm curious why you think this doesn't fit in ytt when kapp does the exact same thing that could have been made from a simple script?

that's an interesting question to think about. my current thoughts around this is that unlike kapp, ytt isnt necessarily the "end of the pipeline", whereas kapp is (e.g. common scenario is ytt | kbld | kapp workflow). arguably kapp shouldnt include app-group functionality either since it could be easily included as a wrapper on top of kapp.

> It doesn't save time on the CI because you still need to setup a CI to push an image from your repository to run the app

point of kapp-controller isnt to save time for anything. it's to _codify_ how particular application should be deployed in a shared format -- App CR (fetch+template+deploy). we also have a plan to provide kapp-controller "reconcile" function in a kapp-controller CLI command so that it's controller-less -- useful for sync CI workflow or local dev.

> it makes configuring the secrets more difficult because another pipeline needs to put those onto the repository

secret mgmt is definitely an interesting subject. different orgs have different way of managing secrets. most recently we have added sops integration to kapp-controller for folks that keep secrets encrypted in the repo. we intend to capture some of the other workflows as they come up as feature requests (i could see vault secret fetching as one possibility). we also have been considering improving secretgen-controller (https://github.com/vmware-tanzu/carvel-secretgen-controller) to have ability to fetch secrets from external sources instead of just generating secrets.

> and you still need to trigger the controller to redeploy your app when an update occurs if I understand correctly.

kapp-controller continuously deploys based on fetch section of App CR. some folks push changes to a git repo (aka gitops style), some folks publish an artifact elsewhere like http or as a docker image that holds configuration (eg imgpkg).

**Comment by DennisDenuto** [comment]
@pivotal-dean and I have read this thread and are planning on talking/presenting this idea with our Product Manager.

As a general rule of thumb, before adding a new feature / new command we want to research into the 'why' behind it. i.e. what use case are we trying to solve, and whether that is a use case we want to solve.

The same applies to whether we remove the kapp app-group command or not.

cc/ @iamhsk

**Comment by cari-lynn** [comment]
Capturing notes from when we talked about this issue in our community meeting here:
 
Currently ytt outputs to stdout for all commands. It's common to use ytt with other tools by piping them together (ytt | kbld | kapp). 
For this feature ytt would write to the file system instead of stdout so that it can respect the directory structure needed. 
That introduces a different UX for the tool, since then for some commands ytt can be piped into other tools and sometimes can not. 

Another point that was raised is that ytt can be used to template data that may contain sensitive information. For example, a user may be templating kubernetes secret via data value overlays like `ytt -f . --data-values-env SECRET`. Since the output may contain secret data then writing to the file system could be a risk. 

We want to support users by providing features that will set them up for success, and keep the possibility of security issues as small as possible by design. For that reason, I believe we should not move forward with this feature.
