### ISSUE TITLE
New merge support doesn't allow overriding

### ISSUE THREAD

**Issue by benmoss** [k14s/ytt#299]
**What steps did you take:**
```
- &foo
  wow: yup
  cool: very
- << : *foo
  wow: nope
```
**What happened:**
`$ ytt -f /tmp/foo.yaml`
```
ytt: Error:
- __ytt_tpl2_start_node: expected key 'wow' to not be specified again (unless 'yaml/map-key-override' annotation is added)
    in <toplevel>
      foo.yaml:5 |   wow: nope
```

**What did you expect:**
yq does the right thing here:

`$ yq eval 'explode(.)' /tmp/foo.yaml`
```
- wow: yup
  cool: very
- cool: very
  wow: nope
```

**Environment:**

- ytt version (use `ytt --version`): 0.31.0

**Comment by joaopapereira** [comment]
Thanks for opening this issue. ytt does not comply with the merge spec so we should definitely look into this issue.
For more information on the spec: https://yaml.org/type/merge.html

Not sure when this issue will be prioritized, let us know if this is something that is blocking your work so that we can review the priority of this issue. Also if you want to try and fix it just send a PR or reach out to us on Slack 😄 

---

Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this bug fixed as soon as possible"
👎 "There are more important bugs to focus on right now"

We are also happy to receive and review Pull Requests if you want to help fix this issue.

**Comment by pivotaljohn** [comment]
This exact issue was also identified in #310.

Since there's developed conversation in _that_ issue, let's use _it_ to drive towards a systemic solution (e.g. one that doesn't require annotations in the case the file is plain YAML).

To keep things clear, we'll call this issue "duplicate", then and merge any further conversation into #310.
