### ISSUE TITLE
multiple @data/values order execution

### ISSUE THREAD

**Issue by juanr2001** [k14s/ytt#300]
Maybe I am doing `ytt` wrong but...:

It seems that `ytt` proccess multiple data/values files like:

```js
config.yml
a.yml
b.yml
```

`ytt` assumes that file `b` will override file `a`, just because `b` is after `a`

Is it possible if `ytt` allows something like this: `ytt -f "b.yml, a.yml"` (where `a` overrides `b`) in the future, so that we can specify what files overrides the others?

If `ytt` already support file order, can someone help me by providing the command?

**Comment by joaopapereira** [comment]
Hello @juanr2001 good question

The way for you to establish order when using data values files or overlays is from left to right of the files that you provide in the command line via `-f` flag and after that by alphabetic order inside folders.
You can find a little bit more information about this in these 2 links:
https://carvel.dev/ytt/docs/latest/lang-ref-ytt-overlay/#overlay-order
https://carvel.dev/ytt/docs/latest/ytt-data-values/#splitting-data-values-into-multiple-files

---
An example, let's assume you have the following 3 files:
`a.yml`
```yaml
#@data/values
---
a: 2
```

`b.yml`
```yaml
#@data/values
---
a: 1
```

`template.yml`
```yaml
#@ load("@ytt:data", "data")
---
result: #@ data.values.a
```

When you execute `-f a.yml -f b.yml`:
```
$ ytt -f template.yml -f a.yml -f b.yml
result: 1
```
When you execute `-f b.yml -f a.yml`:
```
$ ytt -f template.yml -f b.yml -f a.yml
result: 2
```

When you execute `-f .`:
```
$ ytt -f .
result: 1
```

---

We usually advise people when they create the configuration to try to separate it into logical folders so that it can be easier to provide the ordering to `ytt`. An example of that could be something like:
config/config.yml
config/values.yml
config-prod/values.yml

This way you can order by doing `ytt -f config -f config-prod`.

Do you think this helps?

**Comment by juanr2001** [comment]
Thank you @joaopapereira for your quick response!

I attacked an image.

I think `ytt -f template.yml -f b.yml -f a.yml` does not respect this order. Instead it respects the name of the file name in  acending order.


![b_yml_—_test-ytt](https://user-images.githubusercontent.com/11986307/107781707-315fc480-6d16-11eb-954a-18a7e3a9c0b6.png)

**Comment by juanr2001** [comment]
Thank you @joaopapereira for your quick response. I guess I skipped an important concept (overlap).
