### ISSUE TITLE
Symlinking `_ytt_lib` not working

### ISSUE THREAD

**Issue by fcremo** [k14s/ytt#334]
**What steps did you take:**

I'm trying to use the same libraries in multiple templates. Ytt is being invoked on a whole template directory with `ytt -f <dir>`. As an alternative from adding `-f /path/to/_ytt_lib` I tried symlinking it into `<dir>`, since it would be more inconveniente to do that in my use case rather than linking. Ytt is not loading the libaries as I expected, even when using `--dangerous-allow-all-symlink-destinations`.

I suspect ytt does not follow symlinks when handling `_ytt_lib`.

**What happened:**

The attached `.tar.gz` has the following structure:
```
.
├── config1
│   ├── config1.yml
│   └── _ytt_lib -> ../_ytt_lib
├── config2
│   ├── config2.yml
│   └── _ytt_lib
│       └── mylib -> ../../_ytt_lib/mylib
├── config3
│   ├── config3.yml
│   └── mylib.lib.yml -> ../_ytt_lib/mylib/mylib.lib.yml
└── _ytt_lib
    └── mylib
        └── mylib.lib.yml
```
`mylib.lib.yml` contains a function `foo`, and the files under `config<N>` import it as such:

- `config1/config1.yml`: `#@ load("@mylib:mylib.lib.yml", "foo")`
- `config2/config2.yml`: `#@ load("@mylib:mylib.lib.yml", "foo")`
- `config3/config3.yml`: `#@ load("mylib.lib.yml", "foo")`

Invoking `ytt --dangerous-allow-all-symlink-destinations -f config<N>` gives the following results:

**config1**:
```
ytt: Error: 
- cannot load @mylib:mylib.lib.yml: Could not find private library (directory '_ytt_lib' missing?)
    in <toplevel>
      config1.yml:1 | #@ load("@mylib:mylib.lib.yml", "foo")
```

**config2**
```
ytt: Error: 
- cannot load @mylib:mylib.lib.yml: Expected to find library 'mylib', but did not find ''
    in <toplevel>
      config2.yml:1 | #@ load("@mylib:mylib.lib.yml", "foo")
```

**config3** (working as expected)
```
value_from_lib:
- bar
- baz
```

This is the result from `ytt --dangerous-allow-all-symlink-destinations --debug --files-inspect -f config<N>`

**config1**:
```
-  (private false)
  files:
  - _ytt_lib
  - config1.yml
  libraries:
    <none>
### result
- _ytt_lib
- config1.yml
```

**config2**
```
-  (private false)
  files:
  - config2.yml
  libraries:
  - _ytt_lib (private true)
    files:
    - _ytt_lib/mylib
    libraries:
      <none>
```

`config1` and `config2` have similar behavior, but their output with `--debug` differs (1 does not find libraries, 2 does but still fails loading) so I thought it might be useful to include them both. `config2` was an attempt at bypassing the problem with `config1`.

**What did you expect:**

I expected ytt to resolve the symlink to `_ytt_lib` and find the libraries.

**Environment:**

- ytt version (use `ytt --version`): `0.30.0`
- OS (e.g. from `/etc/os-release`): Arch

**Attachments:**

- [ytt_lib_symlink.tar.gz](https://github.com/vmware-tanzu/carvel-ytt/files/6188614/ytt_lib_symlink.tar.gz)

**Comment by StevenLocke** [comment]
This is some excellent investigation! Thanks for putting in that effort.

I think the concern extends beyond your original scope: ytt does not support symlinking directories for input at all, libraries or otherwise.

With a simple example, 

```yaml
#! ~/test/config.yaml

---
a: 1
b: 2
```

`ln -s ~/test/ ~/Desktop`

`ytt -f ~/Desktop/test --dangerous-allow-all-symlink-destinations`

\<no output\>

If we run it with the `--debug` flag, we see that the `test` "file" is simply being treated as a regular file... no contents to template.

```
-  (private false)
  files:
  - test
  libraries:
    <none>
### result
```

If we execute the template command in the source,

`ytt -f ~/test/`

We get the expected output.
```yaml
a: 1
b: 2
```


Hopefully this explains the different output in your config examples.

In config1, the entire _ytt_lib directory is non-existant. Instead there's a file with the same name, so ytt cannot load from it.
In config2, the _ytt_lib directory exists, but has no directories within it, just a file, so again, nothing to be loaded.
Finally, config3, the _file_ is linked, not the directory, which ytt supports.


-----------------------------------

One more example, if we create a config4 directory with a real _ytt_lib folder and mylib subfolder, but a symlinked file within it, we can get the desired functionality. Symlinking files is supported, directories is not.

```
config4
├── _ytt_lib
│   └── mylib
│       └── mylib.lib.yml -> ../../../_ytt_lib/mylib/mylib.lib.yml
└── config4.yml
```
```yaml
#! config4.yml

#@ load("@mylib:mylib.lib.yml", "foo")

---
value_from_lib: #@ foo()
```

`ytt -f config4 --dangerous-allow-all-symlink-destinations`

```yaml
value_from_lib:
- bar
- baz
```

-----------------------

I'm making the assumption (please correct me if I'm wrong!) that your real ask here is about how to share libraries without copying them all over the place. [Vendir](https://carvel.dev/vendir/) (or on [github](https://github.com/vmware-tanzu/carvel-vendir)) may be a possible solution for you.

**Comment by fcremo** [comment]
My bad, I did not consider the possibility that symlinking directories was not a supported feature at all. 
Your assumption is correct, I'll check out vendir, it seems like it might solve the problem. Thanks @StevenLocke!
