### ISSUE TITLE
Text templating `(@= ... @)` whitespaces and strict parsing

### ISSUE THREAD

**Issue by pnsantos** [k14s/ytt#420]
Not sure this is a bug or a limitation but when using text templating to build a YAML key it seems like you cannot have _any_ whitespace whatsoever within the `(@= ... @)` expression if strict parsing is enabled. 

It seems unexpected since it would make more sense for the value within `(@= ... @)` to be evaluated _before_ checking the YAML validity

The [docs](https://carvel.dev/ytt/docs/latest/ytt-text-templating/) seem to imply it's possible to have whitespace:
```
#@ val1 = "val1"
#@ val2 = "val2"

#@yaml/text-templated-strings
---yaml
key:
  nested_key_(@= val1 @): "middle (@= val2 @) after"
```
however when I try this (and use `-s` for strict validation):
```yaml
#@yaml/text-templated-strings
IMAGE_ARG_(@= base_image.alias.replace('-','_') @): #@ ...
```
I got:
```
ytt: Error: 
- cannot load task.lib.yml: Unmarshaling YAML template 'task.lib.yml': yaml: Strict parsing: Strings with whitespace must be explicitly quoted: 'IMAGE_ARG_(@= base_image.alias.replace('-','_') @)'
```
If I change it to be:
```yaml
#@yaml/text-templated-strings
IMAGE_ARG_(@=base_image.alias.replace('-','_')@): #@ ...
```
 (no whitespace before/after the expression within the block) then it works.

This happens with any whitespace (e.g. `replace('-', '_')` also triggers it). If I _don't_ use strict validation then it works (and there's no whitepsace on the YAML key on the final output). 

Using ytt `0.34.0`

**Comment by pivotaljohn** [comment]
👋🏻 @pnsantos.

Solution options first: the best way forward would be to surround the key with quotes:

```yaml
#@ val1 = "val1"
#@ val2 = "val2"

#@yaml/text-templated-strings
---
key:
  "nested_key_(@= val1 @)": "middle (@= val2 @) after"
```
_(fwiw, single quotes work too.)_

As you've noticed, you can eliminate spaces in the expression as well (I personally would find it a bit hard to read).

...

So, what's going on here?

Turns out, `ytt` is behaving as it was designed. That design is to operate on YAML from _within_ the structure. Doing so yields some desirable capabilities: on the outset, we need not be concerned about indentation or escaping to ensure well-formed YAML (not just detecting well-formedness, but _producing_ well-formed YAML). Additional benefits are on their way (e.g. the eminent [Schema](https://carvel.dev/ytt/docs/latest/ytt-schema/) feature depends heavily on operating over structure, not free-form text).

As I think about the consequences of trying to hoist evaluating _some_ expressions prior to parsing, complications arrive pretty quickly:
- in many (common) cases, Starlark variables (like `val1`) are intended to hold [YAML fragments](https://carvel.dev/ytt/docs/latest/lang-ref-yaml-fragment); when/how would these expression be evaluated if that underlying fragment hadn't been parsed yet?
- `@yaml/text-templated-strings` scopes such free-form processing to just the sub-tree it annotates (in the example we're looking at, the whole document is in that scope, but that's presumably because the author knows that the string `(@` or `@)` won't appear anywhere within there that's not intended to be text templating. But if `ytt` were to process text templating _before_ parsing, how would it determine that scope?

It's not that you have unrealistic expectations, @pnsantos... these assumptions about how templating should work are congruent with how many templating engines operate. The pitch from `ytt` is this: if we shift our perspective and template _from within the structure_ a whole set of solutions become available that rest on knowing it's YAML. In that shift, it means trading off the absolute freedom of injecting text _anywhere_ in the stream.

...

So:
1. most importantly, does the proposed solution work for you?
2. have I been able to clearly articulate the motivations for the what and why `ytt` templates structurally?

**Comment by pnsantos** [comment]
> 1. most importantly, does the proposed solution work for you?

:+1:  Only reason I reported was just in case it was unintended but your explanation makes sense. Using the quotes does mess with the highlight colours of vscode-ytt but having the spaces is definitely an improvement on readability.

The arguments in favour of the current behaviour and against changing it make perfect sense. Thanks for taking the time to explain! 

> 2. have I been able to clearly articulate the motivations for the what and why ytt templates structurally?

:+1: perfectly ^_^
