### ISSUE TITLE
ParseIP and ParseCIDR

### ISSUE THREAD

**Issue by tylerschultz** [k14s/ytt#430]
**Describe the problem/challenge you have**

I would like to assert on the ipv4ness or ipv6ness of IPs and CIDRs so that an IPv4 CIDR or address is not passed where an IPv6 address/CIDR is required.

**Describe the solution you'd like**

We propose a `net` module that starts off with `net.parse_ip` and `net.parse_cidr`

net.parse_ip("192.168.0.2", return_error=True) => (ip or None, err_msg_string or None)
ip.is_v4() => True
print(ip) => "192.168.0.2"
ip.is_v6() => False
err_msg_string  => "<error message>"

net.parse_cidr("192.168.0.1/24") => (ip or None, ip_net or None, err_msg_string or None)
ip.is_v4() => True
print(ip) => "192.168.0.1"
ip.is_v6() => False
print(ip_net) => "192.168.0.0/24"
err_msg_string => "string is not a valid CIDR"

**Anything else you would like to add:**

We acknowledge that this interface is nothing like python's parsing functions. We've proposed this interface knowing that it would be implemented with golang.

This is a far from complete proposal, but feels like a starting point that allows for extending later.

This proposal was discussed in this [slack thread](https://kubernetes.slack.com/archives/CH8KCCKA5/p1623436787481700).

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by tylerschultz** [comment]
On the topic of `net.parse_ip("192.168.0.2", return_error=True)`, it was proposed that it return a Tuple.
Does anyone have an opinion on what the function would return if `return_error=False`? Would it force callers to declare the error variable even though they'd prefer it panic?

**Comment by pivotaljohn** [comment]
Thoughts on names (just tossing alternatives out there)...
- instead of `net`, perhaps call the module `ip` — rationale: `net` implies to me network connectivity; `ip` is purely about manipulating Internet Protocol data objects.
  - `ip.parse_addr()`
  - `ip.parse_cidr()`
- individual types: `ipaddress`, `ipnetwork` — a CIDR is the notation that describes a sub-network.

In terms of parse failures...
Another angle on this could be for this module to attempt to parse the string in various ways... and only panic when nothing can be parsed from it...

So, instead of `net.parse_ip()` and `net.parse_cidr()`...what if `net.parse()`:
- first attempts to parse a CIDR,
- failing that attempts to parse a IP
- failing that, panics

...

We could also consider an IP address without an explicit CIDR to have a netmask of `255.255.255.255` (or `/32`)... and so always return a `ipnetwork`...

...

**Comment by pivotaljohn** [comment]
This is currently being designed/developed ==> `discussion`

See #433 for that discussion.

**Comment by pivotaljohn** [comment]
@tylerschultz, @flawedmatrix, and @christianang:

Thank you for all your efforts, here.
