### ISSUE TITLE
Broken 'ytt website' in Windows v0.35.0

### ISSUE THREAD

**Issue by wezzman** [k14s/ytt#456]
**What steps did you take:**
I attempted to run `ytt website` both with and without `--redirect-to-https=false` and the default `--listen-addr`.

**What happened:**
`localhost:8080` shows a completely blank screen with no indication that the connection timed out.

**Anything else you would like to add:**
The `v0.34.0` release correctly displays the playground on the same machine.

I believe that the playground was simply left out of the `v0.35.0` package.

I have not confirmed, but I suspect the same issue applies to the Linux and Darwin packages as well. There was a consistent 0.6M drop in file size between `v0.34.0` and `v0.35.0` for all packages.

**Environment:**

- ytt version (use `ytt --version`): `v0.35.0`
- OS (e.g. from `/etc/os-release`): `Windows 10`

**Comment by cari-lynn** [comment]
Hey @wezzman thanks for bringing this to our attention! It's now fixed for the v0.35.0 release. 

This was a bug from the new github workflow to automate the release process. Turns out the step which generates the website content for `pkg/website/generated.go` in the [`/hack/build.sh`](https://github.com/vmware-tanzu/carvel-ytt/blob/develop/hack/build.sh) script was left out of the [release workflow](https://github.com/vmware-tanzu/carvel-ytt/blob/develop/.github/workflows/release.yml). 

Thanks again, this will be fixed before the next release goes out.

**Comment by wezzman** [comment]
I can confirm that `ytt website` works in the fixed `v0.35.0` package, although it appears to be the `v0.34.0` playground and lacks the "schema" examples from the hosted playground (aka https://carvel.dev/ytt/#playground).

I don't think the older playground is much of an issue. From my perspective, the main use of the playground is as a nice interactive debugger and development tool. Feel free to close this at your leisure.

**Comment by cari-lynn** [comment]
Thanks for all your help with this! We have published a patch release v0.35.1 to address this bug. This is the release we recommend is used. Thank you for being patient with us as we iron out our release process.
