### ISSUE TITLE
📢 No tweet for `v0.35.1` 🙏 📢 

### ISSUE THREAD

**Issue by adriens** [k14s/ytt#461]
# :point_right:Context

On each release, I usually use the official Carvel tweet so I can retweet the announce that embeds the release contents, it's a very easy yet powerful to spread the information.

On the latest [v0.35.1](https://github.com/vmware-tanzu/carvel-ytt/releases/tag/v0.35.1), there actually is no tweet (yet).

# 🚀Requested action

- [x] Please tweet the release 
- [x] Drop the tweet url in that ticket (bonus)

# :page_with_curl:Related stuff

- Chocolatey dedicated https://github.com/adriens/chocolatey-ytt/issues/10

**Comment by aaronshurley** [comment]
Thanks for calling this out, @adriens. Due to the distributed nature of our team, we currently have different folks that cut releases and that post tweets so the timing of these activities doesn't always align immediately. I'll keep this issue open until @microwavables is able to get to this.

In the future, I think this is a great area where we should consider automating :D

**Comment by aaronshurley** [comment]
Tweeted: https://twitter.com/carvel_dev/status/1415342893305376769

**Comment by microwavables** [comment]
@adriens please feel free to ping me [on slack](https://kubernetes.slack.com/archives/CH8KCCKA5) directly if a tweet has yet to go out and you are looking for it. :)

**Comment by adriens** [comment]
You're all doing great, especially for a distributed team...maybe for some on spare/free time.
Thanks for you kind posts.
Now... I only kave to wait for chocolatey to validate the package 😄
