### ISSUE TITLE
Rename module from "github.com/k14s/ytt" to "github.com/vmware-tanzu/carvel-ytt"

### ISSUE THREAD

**Issue by pivotaljohn** [k14s/ytt#585]
**Describe the problem/challenge you have**

We've now received multiple external requests to align the module name with the repo name, including:
- https://github.com/vmware-tanzu/carvel-ytt/issues/583

**Describe the solution you'd like**
Rename the module and all references to it.

**Anything else you would like to add:**
This is part of vmware-tanzu/carvel#153

---

To Do:
- [x] Perform the rename
- [x] Give the Carvel repos a review (example: vmware-tanzu/carvel) to see if any repos are consuming ytt so that they can be updated.
- [x] broadcast this change in slack channels so that any consumers are aware.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by pivotaljohn** [comment]
important-soon: we've had more than one request for this. Placed in the backlog to be strategically occurring when little (no?) other work would be in flight (to minimize the potential for merge conflicts).

**Comment by aaronshurley** [comment]
Let's make sure we broadcast this change in slack channels so that any consumers are aware.

Give the Carvel repos a review (example: vmware-tanzu/carvel) to see if any repos are consuming ytt so that they can be updated.

**Comment by gcheadle-vmware** [comment]
Repos consuming ytt:
- kapp: 
  - [code and go.mod](https://github.com/vmware-tanzu/carvel-kapp/search?q=github.com%2Fk14s%2Fytt)
- vendir:
  - [examples](https://github.com/vmware-tanzu/carvel-vendir/search?q=github.com%2Fk14s%2Fytt&type=code)
- Carvel:
  - [examples](https://github.com/vmware-tanzu/carvel/search?q=github.com%2Fk14s%2Fytt)
- ytt.vim
  - [readme](https://github.com/vmware-tanzu/ytt.vim/search?q=github.com%2Fk14s%2Fytt) 
- vscode-ytt
  - [readme](https://github.com/vmware-tanzu/vscode-ytt/search?q=github.com%2Fk14s%2Fytt)
- lib-4-k8s
  - [example](https://github.com/vmware-tanzu/carvel-ytt-library-for-kubernetes/search?q=github.com%2Fk14s%2Fytt)
- lib-4-k8s-demo
  - [readme](https://github.com/vmware-tanzu/carvel-ytt-library-for-kubernetes-demo/search?q=github.com%2Fk14s%2Fytt)
- kbld:
  - N/A
- imgpkg:
  - N/A
- kapp controller: 
  - N/A

---

directory `examples/integrating-with-ytt/internal-templating/` imports ytt v0.38.0 with module: `github.com/k14s/ytt v0.38.0`. Since v0.40.0 will be the first release with the new module name, this dependency will not need to be updated.

**Comment by gcheadle-vmware** [comment]
Previous slack message from Joao: https://vmware.slack.com/archives/CUK1X0Z8Q/p1643296774183100?thread_ts=1643253820.181400&cid=CUK1X0Z8Q

Slack message to go along with version ytt v0.40.0 release:

Hello ytt users 👋 

As of the release of `ytt` v0.40.0, the go module has been renamed from [github.com/k14s/ytt](http://github.com/k14s/ytt) to [github.com/vmware-tanzu/carvel-ytt](http://github.com/vmware-tanzu/carvel-ytt) so that it matches the repository name where it is stored. Since this might cause disruption in your workflow, v0.40.0 only contains the rename module change and has no feture difference with v0.39.0.

---

slack message for klt-private kapp team:
@ kapp With the upcoming release of ytt v0.40.0, the go module name has changed to [github.com/vmware-tanzu/carvel-ytt](http://github.com/vmware-tanzu/carvel-ytt) . Currently [kapp is using ytt v0.36.0](https://github.com/vmware-tanzu/carvel-kapp/blob/develop/go.mod#L13) in its go.mod so this change should not impact you until you decide to update to v0.40.0.

**Comment by gcheadle-vmware** [comment]
Completed in [ytt v0.40.0](https://github.com/vmware-tanzu/carvel-ytt/releases/tag/v0.40.0)
