### ISSUE TITLE
[question]: Why is accessing a node variable not allowed in text templating

### ISSUE THREAD

**Issue by gabyx** [k14s/ytt#721]
Consider the following:

```yaml
a: "asd"
b: "ggg"

#@yaml/text-templated-strings
all: "(@ .a + .b @)"
```

I would have liked to have access to the current document values `a` and `b` somehow to be able to use them in text templating. Why was that design choice ctaken to dissallow this? Whats the reason behind?

**Comment by mamachanko** [comment]
I cannot speak to the design, but in the meantime, if you are stuck on this, [overlay.replace](https://carvel.dev/ytt/docs/v0.42.0/lang-ref-ytt-overlay/#overlayreplace) could help you to merge a and b into all.

**Comment by pivotaljohn** [comment]
Right: there is no "this" reference.

@cppforlife can elaborate on the thinking behind this specific instance.

In general, I'll say that there's a deliberate attempt to maximize expressiveness while keeping the underlying mechanisms as simple as possible.

There are a couple sources of complexity in such expressions:
- it introduces a path-expression syntax that doesn't currently exist in the tool (so far, all referencing use-cases have been met with structure "expressions" (i.e. through a YAML structure itself);
- in YAML, keys can be values other than strings; the syntax would need to support such cases;
- such syntax would also need to support indexing into array values;
- it wouldn't be hard to write cycles (e.g. `a: (@= .all)`); these would need to be detected or execution timed-out.

In addition, there's a "workaround" that seems reasonable (at least for this example): we're authoring a template, so we're aware that `a:` and `b:` have values that are desired elsewhere. Those values can be hoisted to variables and referenced; ensuring a DAG.

**Comment by pivotaljohn** [comment]
In terms of a solution, @mamachanko rightly pointed to Overlays as a way to update the value of `all:` with an expression. It gets a little complicated because the `@overlay/replace` needs to be placed on the lowest-common ancestor of the node receiving the evaluated expression and the nodes supplying values. Overlays also represent a level of indirection: it's a patch applied after the fact and there's no evidence of it in the original template; one needs to know that the overlay is being applied, somehow.

If it's possible, templating is preferred.

```yaml
#@ a = "asd"
#@ b = "ggg"

a: #@ a
b: #@ b
all: #@ a + b
```
Notes:
- when supplying a *value* for a map item, there's generally no need to create the string in a text template.
- if a template is desired, check out [`string.format()`](https://github.com/google/starlark-go/blob/master/doc/spec.md#string%c2%b7format).
- text templating _is_ required when the *key* for a map item is an expression.

**Comment by pivotaljohn** [comment]
@gabyx — if you have any follow-up questions on this topic or have a suggestion, please feel free to comment on this issue.

In the meantime, closing.
