### ISSUE TITLE
Sorting on overlay array merge

### ISSUE THREAD

**Issue by AyWa** [k14s/ytt#758]
**Describe the problem/challenge you have**

After patching, of a yaml array, the element are not in alphabetics order. It would be nice to have an option to maintains an order

For now I have a patch that looks like that. The goal is to ensure (create if missing) that a key is inside a yaml array.  But with this code, the yaml generated is not in a good order.

```
#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.subset({"kind": "Kustomization"})
---
resources:
  #! we use by=lambda to find equality of values
  #@overlay/merge
  #@overlay/match missing_ok=True,by=lambda indexOrKey, left, right: right in left
  - #@ "{}.{}.yaml".format(data.values.namespace,data.values.project)

```

**Solution**

Maybe there would be a way to add sorting ?

**Comment by mamachanko** [comment]
@AyWa ty for your question!

Overlays usually merge by appending or replacing in-place. They are ignorant of the sorting. That's because the user-defined order may be arbitrarily complex. Alphabetical order is only one possible order.

To achieve your desired outcome, my suggestion is to instead replace the parent node via a custom function. That way you can control whichever sorting you require.

I have prepared [an example on the playground](https://carvel.dev/ytt/#gist:4840509cd73d0180ddc8083b902d66b8) for you. (Alternatively, go to its [gist](https://gist.github.com/mamachanko/4840509cd73d0180ddc8083b902d66b8) directly.)

It produces:

```yaml

kind: Kustomization
resources:
- amazing.coffee.yaml
- boring.stuff.yaml
- fun.mergemania.yaml
- zebra.zulu.yaml

```

Let me know if that helps you.

**Comment by AyWa** [comment]
@mamachanko oh wow, thank you for the quick update !

The gist is really helpful. Thank you for your help. I will close this issue because your solution seems to solve the feature request !!
